### ISSUE TITLE
curl: (22) The requested URL returned error: 401 Unauthorized

### ISSUE THREAD

**Issue by DavidRodHub** [mortensteenrasmussen/docker-registry-manifest-cleanup#11]
**Unable to clean up our private registry using you script. What am I missing.**

**We using a private registry by vmware/harbor**
- https://github.com/vmware/harbor

**Here's the command:**

:~# docker run -it -v /\<path to reg\>/registry:/registry -e REGISTRY_URL=https://docker-reg.mydomain.com -e CURL_INSECURE=true mortensrasmussen/docker-registry-manifest-cleanup

curl: (22) The requested URL returned error: 401 Unauthorized
Could not contact registry at https://docker-reg.mydomain.com - quitting

**Comment by mortensteenrasmussen** [comment]
I haven't tested this on Harbor myself, but you're getting an HTTP 401 Unauthorized for your registry. 

I assume you need to add username and password of a harbor admin user that is allowed to read and write to all repositories. Also, I'm not sure how Harbor stores the files, but if the storage scheme is the same as with Dockers own `registry` container, then it should work IMHO. 

Please note again, I have not tested this, so I wouldn't start doing this on a production registry without having a backup.

If its still relevant and you have further questions, please reopen this ticket.
