### ISSUE TITLE
Script assumes everything is under a repo named 'repos'

### ISSUE THREAD

**Issue by travisgroth** [mortensteenrasmussen/docker-registry-manifest-cleanup#5]
Hi - it looks like this script doesn't account for different repository names.  I'm getting a 404 for everything and realized the name of the repository is always 'repos' rather than the actual name.   Is there something I'm missing?  The result is that I get a 404 for every delete command.

**Comment by mortensteenrasmussen** [comment]
Hi, I'm sorry - this happened in the latest release, I'll release a hotfix very soon (within a few hours).

**Comment by mortensteenrasmussen** [comment]
Thanks for a quick report, and sorry for the inconvenience - a new release is ready, and docker images are updated as well (`latest` and `1.0.3`).

**Comment by travisgroth** [comment]
Thanks for the quick turnaround!
